# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90d486fcc830dc04ff23eab32d1ef41a6e9973f95c8a6d89c3fedbba8dd096772190c2c8c4760c63a5e32608612cd1c9c7fc227d998f2aa666a06fcf08fce165

test:
  secret_key_base: 8c395c14403b0f55fabc9c5ac3694b1a5ef37d8802d71969ed0458cf305bf674b1c5e5c172288dcd6b22089d7257ba351476a01579a9c032712bd2d2eb9270c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
